### ISSUE TITLE
Do you still have a demo for placing orders?

### ISSUE THREAD

**Issue by yosom** [DaanA32/dfx#1]
thinks

**Comment by DaanA32** [comment]
Hi Yosom,

I will create a proper example at some point, but essentially calling the following:
```rust
let mut message = Message::default();
// ...
message.set_tag_value(dfx::tags::Price, 1.0);
// ... other fields
Session::send_to_session(session_id, message).unwrap();
```
You would have to get the session id from the application.

**Comment by DaanA32** [comment]
Proper example:
https://github.com/DaanA32/dfx/blob/example/trade/examples/coinbase/src/main.rs
